#!/bin/bash
#1. Skrypt pobierajacy z pliku "liczby" liczby i segregujacy je na parzyste i nieparzyste i tworzy pliki z nimi
for x in $(cat liczby); do
let r=$x%2
if [ $r -eq 1 ]; then echo $x >> nieparzyste
else echo $x >> parzyste
fi
done

