#!/bin/bash
#komentarz
echo      "          ********************************"         
echo
echo
echo      "          !..!    Artur !! Ziemba     !..!"       
echo
echo
echo      "          ********************************"           
if [ $1 -gt $2 ]; then
			if [ $1 -gt $3 ]; then echo "Największa liczba to" $1
				else echo "Największa liczba to" $3
			fi
elif [ $2 -gt $3 ]; then echo "Największa liczba to" $2
	else echo "Największa liczba to" $3
fi


